/// Accessibility audit findings that existed when the audit was added, as
/// `screen | audit type | element`. The element is its accessibility identifier
/// when it has one, otherwise its label with counts, times, dates, and ages
/// masked (see `findingName` in TrainyAccessibilityAuditUITests).
///
/// The audit fails on any finding that is not listed here. When a screen is
/// fixed, delete its entries: each audit test attaches the entries it no longer
/// reproduces.
let knownAccessibilityIssues: Set<String> = [
    // trips (27)
    "trips | contrast | ETA",
    "trips | contrast | Hayabusa #",
    "trips | contrast | Japan Shinkansen starter catalog · updated <age>",
    "trips | contrast | On time",
    "trips | contrast | Route line, map position, stops, and disruptions",
    "trips | contrast | Starter",
    "trips | contrast | Tohoku Shinkansen",
    "trips | dynamicType | ETA",
    "trips | dynamicType | Japan Shinkansen starter catalog · updated <age>",
    "trips | dynamicType | More active journeys",
    "trips | dynamicType | Next",
    "trips | dynamicType | Platform",
    "trips | hitRegion | Journey progress",
    "trips | textClipped | #:# <am/pm>",
    "trips | textClipped | Alerts off",
    "trips | textClipped | ETA",
    "trips | textClipped | Japan Shinkansen",
    "trips | textClipped | Japan Shinkansen starter catalog · updated <age>",
    "trips | textClipped | Nagoya",
    "trips | textClipped | Next",
    "trips | textClipped | Nozomi #",
    "trips | textClipped | Platform",
    "trips | textClipped | Refresh",
    "trips | textClipped | Route line, map position, stops, and disruptions",
    "trips | textClipped | Share",
    "trips | textClipped | Shin-Osaka",
    "trips | textClipped | Tokyo → Shin-Osaka",

    // search (25)
    "search | contrast | Departure, arrival, duration, transfers, operator, and status",
    "search | contrast | Fast station search",
    "search | contrast | HAK",
    "search | contrast | HIR",
    "search | contrast | KAG",
    "search | contrast | search.result.toki-327",
    "search | dynamicType | Fast station search",
    "search | dynamicType | Favorite stations",
    "search | dynamicType | HAK",
    "search | dynamicType | HIR",
    "search | dynamicType | Hakata",
    "search | dynamicType | Hiroshima",
    "search | dynamicType | Japan Shinkansen",
    "search | dynamicType | KAG",
    "search | dynamicType | Nozomi #",
    "search | dynamicType | Shin-Osaka to Kagoshima-Chuo",
    "search | dynamicType | Tokaido Shinkansen",
    "search | dynamicType | Tokyo to Shin-Osaka",
    "search | dynamicType | Try a search",
    "search | textClipped | Japan Shinkansen / Japan",
    "search | textClipped | Nozomi #",
    "search | textClipped | Shin-Osaka to Kagoshima-Chuo",
    "search | textClipped | Tokaido Shinkansen",
    "search | textClipped | Tokyo to Shin-Osaka",
    "search | textClipped | Train number, station pair, operator, route, or time",

    // search-results (16)
    "search-results | contrast | Japan Shinkansen search is limited to Japan Shinkansen starter catalog. Predicti",
    "search-results | contrast | On time",
    "search-results | contrast | Starter",
    "search-results | contrast | search.result.nozomi-231",
    "search-results | dynamicType | #",
    "search-results | dynamicType | Departure, arrival, duration, transfers, operator, and status",
    "search-results | dynamicType | Matching services",
    "search-results | dynamicType | On time",
    "search-results | dynamicType | Platform",
    "search-results | dynamicType | Starter",
    "search-results | dynamicType | Track",
    "search-results | dynamicType | search.result.nozomi-231",
    "search-results | hitRegion | Clear text",
    "search-results | textClipped | Japan Shinkansen / Japan",
    "search-results | textClipped | Train number, station pair, operator, route, or time",
    "search-results | textClipped | search.result.nozomi-231",

    // stations (28)
    "stations | contrast | # departures · # tracks · # routes",
    "stations | contrast | # shown",
    "stations | contrast | HAK",
    "stations | contrast | Hakata",
    "stations | contrast | KOJ",
    "stations | contrast | KUM",
    "stations | contrast | Kagoshima-Chuo",
    "stations | contrast | Kanazawa",
    "stations | contrast | Kumamoto",
    "stations | contrast | On time",
    "stations | contrast | Search Dutch stations and open proxy-backed departure boards.",
    "stations | dynamicType | # departures · # tracks · # routes",
    "stations | dynamicType | HAK",
    "stations | dynamicType | HIR",
    "stations | dynamicType | Hiroshima",
    "stations | dynamicType | KAN",
    "stations | dynamicType | KOJ",
    "stations | dynamicType | Kagoshima-Chuo",
    "stations | dynamicType | Kanazawa",
    "stations | dynamicType | On time",
    "stations | textClipped | # shown",
    "stations | textClipped | HAK",
    "stations | textClipped | Hakata",
    "stations | textClipped | Hiroshima",
    "stations | textClipped | KOJ",
    "stations | textClipped | Kagoshima-Chuo",
    "stations | textClipped | Kanazawa",
    "stations | textClipped | Station, platform, or route",

    // ns-station-search (5)
    "ns-station-search | contrast | Enter at least two characters or choose a common station.",
    "ns-station-search | contrast | Find an NS station",
    "ns-station-search | contrast | Search Dutch stations, then open a departure board with explicit freshness. NS c",
    "ns-station-search | textClipped | NS departures",
    "ns-station-search | textClipped | ns.stationSearch.field",

    // ns-departures (15)
    "ns-departures | contrast | # fresh NS notice",
    "ns-departures | contrast | Check the station display before boarding.",
    "ns-departures | contrast | Data from Nederlandse Spoorwegen (NS)",
    "ns-departures | contrast | Delayed",
    "ns-departures | contrast | Expected #:#",
    "ns-departures | contrast | Fresh",
    "ns-departures | contrast | NS Reisinformatie API",
    "ns-departures | contrast | On time",
    "ns-departures | contrast | Platform #",
    "ns-departures | contrast | Source",
    "ns-departures | dynamicType | #:#",
    "ns-departures | dynamicType | Delayed",
    "ns-departures | dynamicType | Expected #:#",
    "ns-departures | dynamicType | On time",
    "ns-departures | dynamicType | Platform #",

    // history (8)
    "history | contrast | Tokyo → Shin-Osaka · #h #m",
    "history | contrast | Trip history is stored locally on this device until you share it.",
    "history | textClipped | Japan Shinkansen",
    "history | textClipped | No tracked delays",
    "history | textClipped | Sakura #, #h #m",
    "history | textClipped | Tokyo → Shin-Aomori · #h #m",
    "history | textClipped | Tokyo → Shin-Osaka · #h #m",
    "history | textClipped | Tokyo → Tsuruga · #h #m",

    // settings (9)
    "settings | contrast | Applies to trip cards, station boards, and shared trip text",
    "settings | contrast | Check",
    "settings | contrast | Healthy",
    "settings | contrast | Metric units",
    "settings | contrast | OK",
    "settings | contrast | Provider health was generated at <month> #, # at #:# <am/pm>.",
    "settings | contrast | Saved trips, pins, notification choices, provider and region choices, and displa",
    "settings | contrast | Share crash diagnostics",
    "settings | contrast | Starter catalog is active. Add an ODPT consumer key in the developer configurati",

    // onboarding (5)
    "onboarding | contrast | Curated Shinkansen examples are available without provider credentials",
    "onboarding | contrast | ODPT and JR timetable data is shown as scheduled when those sources return trips",
    "onboarding | contrast | Predictions and vehicle positions only appear when a provider supplies those fee",
    "onboarding | contrast | Skip",
    "onboarding | dynamicType | Skip",
]
